### ISSUE TITLE
Support for lib target with different name than crate.

### ISSUE THREAD

**Issue by cpu** [awslabs/cargo-check-external-types#113]
Hi there, :wave:

I'm trying to use this tool with [rustls/webpki](https://github.com/rustls/webpki). That crate started as a fork of another crate, and so while the crate has the name `rustls-webpki` we [configure the `[lib]` target with the name `webpki`](https://github.com/rustls/webpki/blob/5d17ef06577a14e47a9bbd1151ea5aa6c83a3855/Cargo.toml#L65-L66). 

When running `check-external-types` with this crate (using tip of `main` for both this tool and rustls-webpki) I get an error like:
```
Running rustdoc to produce json doc output...
[src/main.rs:101] err = Error {
    context: "error at src/main.rs:171:14",
    source: Error {
        context: "error at src/cargo.rs:72:65",
        source: Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory",
        },
    },
}
error at src/main.rs:171:14: error at src/cargo.rs:72:65: No such file or directory (os error 2)
```

The not found path isn't printed in the error context, but in this case it's looking for a file with the path `"/home/daniel/Code/Rust/webpki/target/doc/rustls_webpki.json"` to be produced by the `rustdoc` invocation, when the actual path produced by `rustdoc` due to the lib name config is `"/home/daniel/Code/Rust/webpki/target/doc/webpki.json"`.

Would you be open to a PR that adds an additional command line argument to specify the lib name? 

Alternatively, it looks like this information might also be present in the `cargo metadata` JSON, but digging it out might be a little gnarly (If I dig into the `packages` array to find the `name == "rustls-webpki"` entry, then there is an entry in the targets array where `kind` is `[ "lib" ]` and the target's `name` is `webpki`).

**Comment by jdisanti** [comment]
Hello 👋 

I'm definitely open to a PR to fix this. Using cargo metadata would be preferable if possible, but falling back to reading the Cargo.toml also seems acceptable. At some point, it would be nice to add the tool's config directly to the Cargo.toml (see #48), so we'll be reading Cargo.toml at that point anyway.
