### ISSUE TITLE
Upgrade `rustdoc-types`

### ISSUE THREAD

**Issue by BiagioFesta** [awslabs/cargo-check-external-types#130]
Currently, `cargo check-external-types` fails with the following:
```text
[...] The version of rustdoc being used produces JSON format version 28, 
but this tool requires format version 27. [...]
```

That's because rustdocs bumped json-output format to  `version 28`.

`rustdoc-types@v0.24.0` [contains this support change](https://github.com/aDotInTheVoid/rustdoc-types/commit/7d097f0ee048c7b9e390018f67e2abb291ad4ede).

This crate should bump that dependency: https://github.com/awslabs/cargo-check-external-types/blob/4bbf5a80fced7e11fdf855537b4202e225596f67/Cargo.toml#L16

To
```
rustdoc-types = "0.24.0"
```

**Comment by jdisanti** [comment]
We definitely need to upgrade, but for future reference, you should pin the nightly version you use in CI to the one listed in the README (currently nightly-2023-10-10) so that you don't get caught off guard in the future.

**Comment by jdisanti** [comment]
rustdoc-types has been updated to 0.24 in the [v0.1.11](https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.11) release (against nightly-2024-02-07).
