### ISSUE TITLE
Typo in GitHub description

### ISSUE THREAD

**Issue by baldoalessandro** [awslabs/cargo-check-external-types#159]
The GitHub description says:

> Static analysis tool for Rust library authors to set and verify which types from other libraries are allowed to be are exposed in their public API. 

it probably should be :
> Static analysis tool for Rust library authors to set and verify which types from other libraries are allowed to be ~are~ exposed in their public API. 

PS: in the README it says:

> is a static analysis tool for Rust library authors to set and verify which types from other libraries are allowed to be exposed in their public API ...

🙂 great crate by the way !

**Comment by jdisanti** [comment]
Thank you! Fixed.
