### ISSUE TITLE
Use `package.metadata` instead of external config file

### ISSUE THREAD

**Issue by thomaseizinger** [awslabs/cargo-check-external-types#48]
Cargo has support for storing data of external tools within the manifest file: https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table

It would be nice to store the allowed external types in there instead of in an additional file.

**Comment by jdisanti** [comment]
I like it. This could be implemented backwards compatibly too: if a config file argument is given, use it, otherwise fallback to the `Cargo.toml` file. If you're interested in contributing this, I would definitely welcome it.

**Comment by thomaseizinger** [comment]
> If you're interested in contributing this, I would definitely welcome it.

I am unlikely to find time for it anytime soon, sorry.
